# Generated by Django 2.0.4 on 2018-04-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180418_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='profile',
        ),
    ]
