# Generated by Django 2.0.4 on 2018-04-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_fans', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_icons', to='api.Profile'),
        ),
    ]
