# Generated by Django 2.0.4 on 2018-04-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180419_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendship',
            new_name='Relation',
        ),
        migrations.AlterModelTable(
            name='relation',
            table='relations',
        ),
    ]
