# Generated by Django 2.0.4 on 2018-04-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180419_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='tagpost_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tagpost_tags', to='api.Post'),
        ),
        migrations.AddField(
            model_name='relation',
            name='tagpost_tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tagpost_posts', to='api.Tag'),
        ),
    ]
