# Generated by Django 2.0.4 on 2018-04-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180419_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='tagprofile_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tagprofile_tags', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='relation',
            name='tagprofile_tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tagprofile_profiles', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_tos', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='froms_to', to='api.Profile'),
        ),
    ]
