# Generated by Django 2.0.4 on 2018-04-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180419_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
