# Generated by Django 2.0.4 on 2018-04-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180419_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='from_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_tos', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagpost_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagpost_tags', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagpost_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagpost_posts', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagprofile_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagprofile_tags', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagprofile_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagprofile_profiles', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='froms_to', to='api.Profile'),
        ),
    ]
