# Generated by Django 2.0.4 on 2018-04-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180420_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='from_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_tos_rs', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagpost_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagpost_tags_rs', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagpost_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagpost_posts_rs', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagprofile_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagprofile_tags_rs', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tagprofile_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagprofile_profiles_rs', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='froms_to_rs', to='api.Profile'),
        ),
    ]
